name: Feature Request
description: Suggest a new feature for SelfMemory
title: "[FEATURE] "
labels: ["enhancement", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a new feature! Please fill out this form to help us understand your request.

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please check these boxes before submitting your feature request.
      options:
        - label: I have searched existing issues to make sure this is not a duplicate
          required: true
        - label: I have checked the roadmap to see if this is already planned
          required: true
        - label: This feature would be useful to other users, not just my specific use case
          required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Description
      description: Is your feature request related to a problem? Please describe.
      placeholder: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see implemented.
      placeholder: A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Have you considered any alternative solutions or workarounds?
      placeholder: A clear and concise description of any alternative solutions or features you've considered.

  - type: textarea
    id: use_case
    attributes:
      label: Use Case
      description: Describe your specific use case and how this feature would help.
      placeholder: |
        Describe your use case:
        1. What are you trying to accomplish?
        2. How would this feature help?
        3. What would the workflow look like?
    validations:
      required: true

  - type: textarea
    id: api_example
    attributes:
      label: Proposed API
      description: If applicable, show what you think the API should look like.
      render: python
      placeholder: |
        from selfmemory import Memory

        memory = Memory()
        # Your proposed API usage
        result = memory.new_feature(...)

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What category does this feature fall into?
      options:
        - Core SDK functionality
        - Search and filtering
        - Storage backends
        - API server features
        - Configuration and setup
        - Security and authentication
        - Performance improvements
        - Documentation
        - Developer tools
        - Integration with other services
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature for your use case?
      options:
        - Nice to have - Would be useful but not critical
        - Important - Would significantly improve my workflow
        - Critical - Blocking my ability to use SelfMemory effectively
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the feature request here.
      placeholder: Any additional information that would help understand this feature request...

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you be willing to help implement this feature?
      options:
        - label: I would be willing to implement this feature
        - label: I would be willing to help test this feature
        - label: I would be willing to help with documentation
        - label: I would be willing to provide feedback during development
