#!/usr/bin/env python
"""Seed a development user, organization, project and API key straight into Mongo.

Creating an API key through the API requires an authenticated session, which
requires Ory Kratos. That is a lot of infrastructure to stand up just to click
through the endpoints, so this writes the same documents the API would and
prints the key.

    uv run python scripts/dev_seed_api_key.py

Development only. It mints a credential without going through auth, so it has
no place anywhere but a local machine -- it refuses to run against a non-local
MongoDB for that reason.
"""

from __future__ import annotations

import argparse
import os
import secrets
import string
import sys
from datetime import datetime, timezone
from pathlib import Path

from pymongo import MongoClient

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from server.utils.crypto import hash_api_key  # noqa: E402

LOCAL_HOSTS = ("localhost", "127.0.0.1", "::1", "mongo", "mongodb")


def generate_api_key() -> tuple[str, str, str]:
    alphabet = string.ascii_letters + string.digits
    api_key = "sk_im_" + "".join(secrets.choice(alphabet) for _ in range(40))
    return api_key, hash_api_key(api_key), api_key[:10] + "..."


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--email", default="dev@localhost")
    parser.add_argument("--org", default="Dev Org")
    parser.add_argument("--project", default="Dev Project")
    parser.add_argument(
        "--mongodb-uri",
        default=os.getenv("MONGODB_URI", "mongodb://localhost:27017/selfmemory"),
    )
    args = parser.parse_args()

    if not any(host in args.mongodb_uri for host in LOCAL_HOSTS):
        parser.error(
            "refusing to seed a credential into a non-local MongoDB: "
            f"{args.mongodb_uri}"
        )

    client = MongoClient(args.mongodb_uri)
    db = client.get_default_database()
    now = datetime.now(timezone.utc)

    # The Kratos identity this user would have had. Nothing validates it while
    # authenticating with an sk_im_ key, so a stable fake is enough.
    kratos_id = f"dev-{secrets.token_hex(8)}"

    user_id = db.users.insert_one(
        {
            "email": args.email,
            "kratosId": kratos_id,
            "name": "Dev User",
            "isActive": True,
            "createdAt": now,
        }
    ).inserted_id

    org_id = db.organizations.insert_one(
        {
            "name": args.org,
            "ownerId": kratos_id,
            "createdAt": now,
        }
    ).inserted_id

    project_id = db.projects.insert_one(
        {
            "name": args.project,
            "organizationId": org_id,
            "ownerId": kratos_id,
            "createdAt": now,
        }
    ).inserted_id

    api_key, key_hash, key_prefix = generate_api_key()
    db.api_keys.insert_one(
        {
            "name": "dev-seed",
            "userId": kratos_id,
            "projectId": project_id,
            "organizationId": org_id,
            "keyHash": key_hash,
            "keyPrefix": key_prefix,
            "permissions": {
                "canRead": True,
                "canWrite": True,
                "canDelete": True,
                "canInvite": False,
            },
            "isActive": True,
            "autoGenerated": True,
            "expiresAt": None,
            "createdAt": now,
            "lastUsed": None,
        }
    )

    print("Seeded. Put these in bruno/environments/local.bru:\n")
    print(f"  apiKey:    {api_key}")
    print(f"  projectId: {project_id}")
    print(f"  orgId:     {org_id}")
    print(f"\n(user _id {user_id}, kratosId {kratos_id})")


if __name__ == "__main__":
    main()
