name: selfmemory-mcp-dev

services:
  selfmemory-mcp:
    build:
      context: ..  # Set context to parent directory
      dockerfile: selfmemory-mcp/Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    networks:
      - selfmemory_network
    volumes:
      - .:/app                           # MCP server code. This allows to reload the app when the server code is updated
      - ../selfmemory:/app/packages/selfmemory  # SelfMemory library. This allows to reload the app when the library code is updated
    depends_on:
      selfmemory-server:
        condition: service_started
      qdrant:
        condition: service_started
      ollama:
        condition: service_started
    command: python main.py
    environment:
      - PYTHONDONTWRITEBYTECODE=1  # Prevents Python from writing .pyc files
      - PYTHONUNBUFFERED=1  # Ensures Python output is sent straight to terminal

  selfmemory-server:
    build:
      context: ..  # Set context to parent directory
      dockerfile: server/Dockerfile
    ports:
      - "8081:8081"
    env_file:
      - .env
    networks:
      - selfmemory_network
    depends_on:
      mongo:
        condition: service_started
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1

  mongo:
    image: mongo:7
    restart: on-failure
    networks:
      - selfmemory_network
    environment:
      - MONGO_INITDB_DATABASE=selfmemory
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

  qdrant:
    image: qdrant/qdrant:latest
    restart: on-failure
    networks:
      - selfmemory_network
    volumes:
      - qdrant_data:/qdrant/storage
    ports:
      - "6333:6333"

  ollama:
    image: ollama/ollama:latest
    restart: on-failure
    networks:
      - selfmemory_network
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11434:11434"
    # Pull the embedding model on startup
    command: >
      sh -c "ollama serve &
             sleep 10 &&
             ollama pull nomic-embed-text &&
             wait"

volumes:
  mongo_data:
  qdrant_data:
  ollama_data:

networks:
  selfmemory_network:
    driver: bridge
